# Generated by Django 5.2.6 on 2026-04-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_paymentlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("percent", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "orders",
                    models.ManyToManyField(
                        blank=True, related_name="discounts", to="shop.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("percent", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "orders",
                    models.ManyToManyField(
                        blank=True, related_name="taxes", to="shop.order"
                    ),
                ),
            ],
        ),
    ]
