# Generated by Django 5.2.6 on 2026-04-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_item_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="stripe_coupon_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tax",
            name="stripe_tax_rate_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
